# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(20, 70, 51, 41))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 120, 51, 41))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(20, 170, 51, 41))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 70, 51, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(90, 120, 51, 41))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 170, 51, 41))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(160, 70, 51, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(160, 120, 51, 41))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(160, 170, 51, 41))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_target_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_5.setGeometry(QtCore.QRect(90, 350, 51, 41))
        self.lineEdit_target_5.setObjectName("lineEdit_target_5")
        self.lineEdit_target_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_9.setGeometry(QtCore.QRect(160, 400, 51, 41))
        self.lineEdit_target_9.setObjectName("lineEdit_target_9")
        self.lineEdit_target_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_1.setGeometry(QtCore.QRect(20, 300, 51, 41))
        self.lineEdit_target_1.setObjectName("lineEdit_target_1")
        self.lineEdit_target_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_8.setGeometry(QtCore.QRect(90, 400, 51, 41))
        self.lineEdit_target_8.setObjectName("lineEdit_target_8")
        self.lineEdit_target_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_2.setGeometry(QtCore.QRect(90, 300, 51, 41))
        self.lineEdit_target_2.setObjectName("lineEdit_target_2")
        self.lineEdit_target_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_3.setGeometry(QtCore.QRect(160, 300, 51, 41))
        self.lineEdit_target_3.setObjectName("lineEdit_target_3")
        self.lineEdit_target_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_4.setGeometry(QtCore.QRect(20, 350, 51, 41))
        self.lineEdit_target_4.setObjectName("lineEdit_target_4")
        self.lineEdit_target_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_7.setGeometry(QtCore.QRect(20, 400, 51, 41))
        self.lineEdit_target_7.setObjectName("lineEdit_target_7")
        self.lineEdit_target_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_target_6.setGeometry(QtCore.QRect(160, 350, 51, 41))
        self.lineEdit_target_6.setObjectName("lineEdit_target_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 470, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(390, 90, 51, 51))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_10 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_10.setGeometry(QtCore.QRect(390, 140, 51, 51))
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.graphicsView_11 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_11.setGeometry(QtCore.QRect(390, 190, 51, 51))
        self.graphicsView_11.setObjectName("graphicsView_11")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_4.setGeometry(QtCore.QRect(440, 90, 51, 51))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_5.setGeometry(QtCore.QRect(440, 140, 51, 51))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_12 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_12.setGeometry(QtCore.QRect(440, 190, 51, 51))
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.graphicsView_7 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_7.setGeometry(QtCore.QRect(490, 90, 51, 51))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_8.setGeometry(QtCore.QRect(490, 140, 51, 51))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_9 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_9.setGeometry(QtCore.QRect(490, 190, 51, 51))
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 290, 91, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 380, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 380, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "源布局："))
        self.label_2.setText(_translate("MainWindow", "目标布局："))
        self.pushButton.setText(_translate("MainWindow", "计算解法"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "演示步骤"))
        self.pushButton_3.setText(_translate("MainWindow", "停止演示"))

